import { Inter } from "next/font/google";
import {Urbanist} from "next/font/google";
import "../../node_modules/bootstrap/dist/css/bootstrap.css"; 
import '@fortawesome/fontawesome-free/css/all.min.css';
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";



import "./globals.css";
import "./custom.css";

const inter = Inter({ subsets: ["latin"] }); 
const urbanist = Urbanist({ subsets: ["latin"] }); 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>{children}</body>
    </html>
  );
}
